import random
import requests
import json

from copyleaks.copyleaks import Copyleaks
from copyleaks.exceptions.command_error import CommandError
from fpdf import FPDF

#EMAIL_ADDRESS = 'wardg6company@gmail.com'  
EMAIL_ADDRESS= 'hassan.n.afif@gmail.com'

#KEY = 'ab6761f5-9de6-4dad-be60-ab60190f6712' 
#'b079479c-fab3-4c7b-ac89-7f70df9d59a3'
KEY = '8931adbf-b8ee-4868-b694-3e01dce8c9b8'
try:
    auth_token = Copyleaks.login(EMAIL_ADDRESS, KEY)
except CommandError as ce:
    response = ce.get_response()
    print(f"An error occurred (HTTP status code {response.status_code}):")
    print(response.content)
    exit(1)



# Submeting and exporting needed data


scan_id = random.randint(100, 100000)

headers = {
    'Content-type': 'application/json',
    'Authorization': f"Bearer {auth_token['access_token']}"
}

with open('sample.txt') as file:
    f = file.read()

scan_file = json.dumps({'text':f})

response = requests.post('https://api.copyleaks.com/v2/writer-detector/{scan_id}/check', headers=headers, data=scan_file)

txt = response.content
txt = json.loads(txt)
results = txt['results']
ai = txt['summary']['ai']

probapility = str(round(results[0]['probability'] * 100)) + '%'
print("Generated By AI" if ai > 0 else "Free of Ai generated content")
print(f'Plagiarism rate: {probapility}')


